= My Async.js Cheatsheet
:hp-tags: english, tech, js

This cheatsheet's aim is to simplify the Aync.js library docs. However the complete docs can be found at https://github.com/caolan/async.

== About Async.js

Async is a utility module which provides straight-forward, powerful functions for working with asynchronous JavaScript. Although originally designed for use with Node.js and installable via npm install async, it can also be used directly in the browser.

=== async.each(`arr`, `iterator`, `[callback]`)

Applies the function `iterator` to each item in `arr`, in parallel. The `iterator` is called with an item from the list, and a `callback` for when it has finished. If the `iterator` passes an error to its callback, the main `callback` (for the each function) is immediately called with the error.

Note, that since this function applies `iterator` to each item in parallel, there is no guarantee that the iterator functions will complete in order.

*Arguments*

1. `arr` (Array): An array to iterate over.
2. `iterator(item, next)` (Function): A function to apply to each item in arr. The iterator is passed a next(err) which must be called once it has completed. If no error has occurred, the next should be run without arguments or with an explicit null argument. The array index is not passed to the iterator. If you need the index, use forEachOf.
3. `callback(err)` (Function): A callback which is called when all iterator functions have finished, or an error occurs.

*Example*

```
// assuming openFiles is an array of file names
async.each(openFiles, function (file, next) {

  // Perform operation on file here.
  console.log('Processing file ' + file);

  if( file.length > 32 ) {
      console.log('This file name is too long');
      next('File name too long');
  } else {
      // Do work to process file here
      console.log('File processed');
      next();
  }

}, function (err){
    // if any of the file processing produced an error, err would equal that error
    if(err) {
        // One of the iterations produced an error.
        // All processing will now stop.
        console.log('A file failed to process');
        console.dir(err);
    } else {
        console.log('All files have been processed successfully');
    }
});
```

*Flowcharts*

image::async/each.png[async.each flowchart]

image::async/each_error.png[async.each error flowchart]

== Asynchronous Control Flow

=== async.series(`tasks`, `[callback]`)

Run the functions in the `tasks` array in series, *each one running once the previous function has completed*. If any functions in the series pass an error to its callback, no more functions are run, and `callback` is immediately called with the value of the error. Otherwise, `callback` receives an array of results when tasks have completed.

*Arguments*

1. `tasks` (Array|Object): An array or object containing functions to run. Each function is passed a next(err, result) which it must call on completion with an error err (which can be null) and an optional result value.
2. `callback(err, results)` (Function): An optional callback to run once all the functions have completed. This function gets a results array (or object) containing all the result arguments passed to the task callbacks.

*Example*

```
async.series([
    function(next){
        // do some stuff ...
        next(null, 'one');
    },
    function(next){
        // do some more stuff ...
        next(null, 'two');
    }
],
// optional callback
function (err, results){
    // results is now equal to ['one', 'two']
});
```

*Flowcharts*

image::async/series.png[async.series flowchart]

image::async/series_error.png[async.series error flowchart]

=== async.waterfall(`tasks`, `[callback]`)

Runs the `tasks` array of functions in series, *each passing their results to the next in the array*. However, if any of the tasks pass an error to their own callback, the next function is not executed, and the main `callback` is immediately called with the error.

*Example*

```
async.waterfall([
    function (next) {
        next(null, 'one', 'two');
    },
    function (arg1, arg2, next) {
      // arg1 now equals 'one' and arg2 now equals 'two'
        next(null, 'three');
    },
    function (arg1, next) {
        // arg1 now equals 'three'
        next(null, 'done');
    }
], function (err, result) {
    // result now equals 'done'
});
```

*Flowcharts*

image::async/waterfall.png[async.waterfall flowchart]

image::async/waterfall_error.png[async.waterfall error flowchart]

=== async.parallel(`tasks`, `[callback]`)

Run the `tasks` array of functions in parallel, *without waiting until the previous function has completed*. If any of the functions pass an error to its callback, the main `callback` is immediately called with the value of the error. Once the tasks have completed, the results are passed to the final callback as an array.

*Example*

```
async.parallel([
    function (next){
        setTimeout(function(){
            next(null, 'one');
        }, 200);
    },
    function (next){
        setTimeout(function(){
            next(null, 'two');
        }, 100);
    }
],
// optional callback
function (err, results){
    // the results array will equal ['one','two'] even though
    // the second function had a shorter timeout.
});
```

*Flowcharts*

image::async/parallel.png[async.parallel flowchart]

image::async/parallel_error.png[async.parallel error flowchart]

=== async.auto(`arr`, `[callback]`)

At first, I was a little be scared about this one but it's finally really easy to understand.

What if you need to chain parallel AND series in the same flow?